version: 2
jobs:
  checkout_code:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/kubermatic/machine-controller
    steps:
      - checkout
      - save_cache:
          key: repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - /go/src/github.com/kubermatic/machine-controller

  install-dependencies:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/kubermatic/machine-controller
    steps:
      - restore_cache:
          key: repo-{{ .Environment.CIRCLE_SHA1 }}
      - run: go get -u github.com/golang/dep/cmd/dep
      - run: dep ensure -vendor-only
      - save_cache:
          key: vendor-{{ checksum "Gopkg.lock" }}
          paths:
            - /go/src/github.com/kubermatic/machine-controller/vendor
  test:
    docker:
      - image: docker:stable
    working_directory: /go/src/github.com/kubermatic/machine-controller
    steps:
      - restore_cache:
          key: repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: vendor-{{ checksum "Gopkg.lock" }}
      - setup_remote_docker
      - run: apk update && apk add make bash git
      - run: |
          set -e
          docker create -v /go/src/github.com/kubermatic/machine-controller --name vol-container alpine /bin/true
          docker cp . vol-container:/go/src/github.com/kubermatic/machine-controller/
          export USE_VOLUME_CONTAINER=true && make test-unit-nodep

  build:
    docker:
      - image: docker:stable
    working_directory: /go/src/github.com/kubermatic/machine-controller
    steps:
      - restore_cache:
          key: repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: vendor-{{ checksum "Gopkg.lock" }}
      - setup_remote_docker
      - run: apk update && apk add make bash git
      - run: |
          set -e
          docker create -v /go/src/github.com/kubermatic/machine-controller --name vol-container alpine /bin/true
          docker cp . vol-container:/go/src/github.com/kubermatic/machine-controller/
          export USE_VOLUME_CONTAINER=true && make machine-controller-nodep
          docker cp vol-container:/go/src/github.com/kubermatic/machine-controller/machine-controller .
      - save_cache:
          key: machine-controller-{{ .Revision }}
          paths:
            - machine-controller

  printer:
    docker:
      - image: docker:stable
    steps:
      - run: echo "printing git_tag:"
      - run: echo $GIT_TAG
      - run: echo "printing circle_tag:"
      - run: echo $CIRCLE_TAG
      - run: echo "printing circle_branch:"
      - run: echo $CIRCLE_BRANCH


  publish:
    docker:
      - image: docker:stable
    working_directory: /go/src/github.com/kubermatic/machine-controller
    steps:
      - restore_cache:
          key: repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: machine-controller-{{ .Revision }}
      - setup_remote_docker
      - run: apk update && apk add make bash git
      - run: |
          set -e
          export GIT_TAG=$CIRCLE_TAG
          docker login -u "${DOCKERHUB_USER}" -p "${DOCKERHUB_PASS}"
          make docker-image-nodep

workflows:
  version: 2
  build:
    jobs:
      - printer:
          filters:
            tags:
              only: /.*/
      - checkout_code:
          filters:
            tags:
              only: /.*/
      - install-dependencies:
          requires:
            - checkout_code
          filters:
            tags:
              only: /.*/
      - test:
          requires:
            - install-dependencies
          filters:
            tags:
              only: /.*/
      - build:
          requires:
            - install-dependencies
            - printer
          filters:
            tags:
              only: /.*/
      - publish:
          requires:
            - build
          filters:
            branches:
              only:
                - master
##  tagged-build:
##    jobs:
##      - build:
##          filters:
##            branches:
##              ignore: /.*/
##            tags:
##              only: /.*/
